### ISSUE TITLE
Artist Offer

### ISSUE THREAD

**Issue by AliHassan3A** [NotCryptid/notcryptid.github.io#1]
Hi Cryptid,

I hope this message finds you well. My name is Ali, and I represent 3A Studios. We’ve been following your incredible work as a graphic designer and are really impressed by your talent. Given your skills, we would love to offer you an exciting opportunity.

We are currently looking for a graphic designer to create and animate characters for our project, *Chase Zone*. The tasks will include designing characters and creating animations for actions such as walking, running, dodging, falling, and executing superpowers. Your artistic flair would be a phenomenal addition to our team.

Additionally, if you have experience with Python and Godot, we might also have a coding position available for you. We value versatility and are always looking for multi-talented individuals to join our crew.

I initially tried reaching out to you on Discord but didn't receive a response. We truly hope you’ll consider this offer and join 3A Studios. Thank you for your understanding, and we look forward to potentially working together!

Best regards,  
Ali  
3A Studios

( Offer generated by 3A AI, AI bot Created by Ali )

**Comment by NotCryptid** [comment]
No

**Comment by AliHassan3A** [comment]
Hi Cryptid,

Thank you for getting back to us. We completely understand and appreciate your honesty. If you ever reconsider or if your availability changes, please know our doors are always open for talented individuals like yourself.

We wish you all the best in your current and future endeavors. Keep creating amazing art, and perhaps our paths will cross again someday.

Thank you once again for your time.

Best regards,
Ali
3A Studios
